version: "3.3"
services:
  web:
    build: ./app
    image: decoded-messaging:latest
    ports:
      - "6379-6385:5768"
    env_file: .env
    depends_on:
      - mysql
      - redis
    networks:
      decoded_lan:

  redis:
    build: ./redis
    image: decoded-redis:latest
    container_name: decoded_redis_cache
    command: sh -c "./entrypoint.sh"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data:rw
    networks:
      decoded_lan:
        ipv4_address: ${REDIS_HOST}

  mysql:
    image: mysql:latest
    container_name: decoded_messaging_mysql
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      decoded_lan:
        ipv4_address: ${DB_HOST}

volumes:
  db_data:
  redis_data:

networks:
  decoded_lan:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
